### ISSUE TITLE
Alternatives to "containerConfig"

### ISSUE THREAD

**Issue by joezimjs** [redradix/kontainer#4]
I was wondering if you had any ideas for an alternative to registering all of the modules in a single `containerConfig` file. It seems like a large application would find this file expanding beyond maintainability. I've thought about having the modules register themselves, but then they never actually get registered, because you go straight to the container without having `require`d the module in the first place...

Any ideas?

**Comment by cdelaorden** [comment]
Hi, thanks for participating

Given the fact that the container itself acts as a Singleton, you could simply split the container config between many files. That way you could have one file for lower-level dependencies and different files for higher-level dependencies.

The order is not important as the container will always resolve all registered dependencies before handling you the final product.

In my experience, however, having a single file with comments has not been a problem, as it's useful to have your dependency names "magic strings" around to avoid typos, and because you'll usually end ip with your module list "sorted" like the following:
- config files (no dependencies at the top)
- infrastructure modules (with config dependencies): Express, databases/ORM, base socket.io server for example.
- service modules - which normally depend on infrastructure (like the TodoService in the example)
- business/use-case oriented modules - like the TodoApi in the express example, depending on both infrastructure and service modules.

Hope this helps, don't hesitate to comment with your specific needs, any ideas are welcome of course. :)

**Comment by joezimjs** [comment]
I haven't experimented with it at all. I just looked at it and some thoughts came to mind. It just doesn't seem like good practice to have a single file determine and `require` all of these dependencies for a couple reasons:
- If you remove the need for a dependency that is registered in that file, it can easily be forgotten, so you end requiring and registering dependencies that are no longer used
- I've always liked the fact that the dependency tree can be built by having dependents import their dependencies because then you don't have to worry about the order of files or whether or not you have everything you need or if you're including things you don't need. In other words, you're "guaranteed" to have what you need and to exclude things you don't need.

Of course the DI/IoC approach is great for decoupling and super great for mocking and stubbing in tests. I guess the big thing is deciding what should go in the container and what shouldn't. Obviously, you don't want everything in there. I guess I'll have to work with it for a while to really know if it's a big issue.
